name: Continous Integration

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check types and lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Check types
        run: npx tsc --noEmit --noErrorTruncation --pretty false --incremental false
      - name: Run eslint
        run: npx eslint .
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm test -- --coverage
      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
